# Generated by Django 5.0.2 on 2025-07-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_finalize_brand_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TIN ID'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='vat_classification',
            field=models.CharField(choices=[('VAT', 'VAT-inclusive'), ('NON_VAT', 'NON-VAT'), ('BOTH', 'Both VAT and NON-VAT')], default='VAT', help_text='VAT classification for tax purposes', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
    ]
