# Generated by Django 5.0.2 on 2025-07-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_update_brand_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='inventory_brand',
        ),
    ]
