# Generated by Django 5.0.2 on 2025-07-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_update_receive_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Return', 'Return'), ('Receive Products', 'Receive Products'), ('Return goods', 'Return goods'), ('Dispatch goods', 'Dispatch goods'), ('Reserve goods', 'Reserve goods'), ('Manual correction', 'Manual correction')], max_length=20),
        ),
    ]
