# Generated by Django 5.0.2 on 2025-07-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cost_tier',
        ),
    ]
