# Generated by Django 5.0.2 on 2025-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_phase1_restructure_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
