# Generated by Django 5.0.2 on 2025-08-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_make_model_number_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'brand')},
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='model_number',
        ),
    ]
