# Generated by Django 5.0.2 on 2025-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_model_number_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOMING', 'Incoming - Stock In from Brand'), ('OUTGOING', 'Outgoing - Stock Out to Customer'), ('ADJUSTMENT', 'Manual Inventory Adjustment')], help_text='Type of transaction: incoming stock or outgoing stock', max_length=20),
        ),
    ]
