# Generated by Django 5.0.2 on 2025-09-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_add_adjustment_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(help_text='Auto-generated batch number for the item, starting from 1.')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='The cost price of items in this batch.', max_digits=10)),
                ('initial_quantity', models.PositiveIntegerField(help_text='The initial quantity of items in this batch.')),
                ('remaining_quantity', models.PositiveIntegerField(help_text='The quantity of items remaining in this batch.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.item')),
                ('transaction', models.ForeignKey(blank=True, help_text='The incoming transaction that created this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.transaction')),
            ],
            options={
                'verbose_name': 'Item Batch',
                'verbose_name_plural': 'Item Batches',
                'db_table': 'inventory_item_batch',
                'ordering': ['item', 'batch_number'],
                'unique_together': {('item', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The specific batch this item is from (for outgoing transactions).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itembatch'),
        ),
    ]
