# Generated by Django 5.0.2 on 2025-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_item_batch_tracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
