# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_add_unique_constraints_and_remove_transaction_item_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="cost_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SRP", "Suggested Retail Price"),
                    ("RD", "Regional Distributor"),
                    ("PD", "Provincial Distributor"),
                    ("DD", "District Distributor"),
                    ("CD", "City Distributor"),
                    ("RS", "Reseller"),
                    ("SUB-RS", "Sub-Reseller"),
                ],
                help_text="The pricing tier at which this user purchases products. Determines their selling restrictions.",
                max_length=10,
                null=True,
            ),
        ),
    ]
